version: "3"

services:
  uol_wk7_camel_app:
    build: "./"
    container_name: "uol_wk7_camel_app"
    volumes:
      - "./inbox:/opt/camel-app/inbox:rw"
      - "./outbox:/opt/camel-app/outbox:rw"
    links:
      - "uol_wk7_mongodb"

  uol_wk7_mongodb:
    image: mongo:latest
    container_name: "uol_wk7_mongodb"
    environment:
      - "MONGO_DATA_DIR=/data/db"
      - "MONGO_LOG_DIR=/dev/null"
    volumes:
      - "./data:/data/db:rw"
    ports:
      - "27017:27017"
    command: "mongod --smallfiles"
