version: "3"

services:
  uol_wk7_camel_app:
    build: "./"
    container_name: "uol_wk7_camel_app"
    volumes:
      - "./inbox:/opt/camel-app/inbox:rw"
    networks:
      cluster:
        ipv4_address: "172.66.7.7"

  uol_wk7_mongodb:
    image: mongo:latest
    container_name: "uol_wk7_mongodb"
    environment:
      - "MONGO_DATA_DIR=/data/db"
      - "MONGO_LOG_DIR=/dev/null"
    volumes:
      - "./data:/data/db:rw"
    ports:
      - "27017:27017"
    command: "mongod --smallfiles"
    networks:
      cluster:
        ipv4_address: "172.66.9.9"

networks:
  cluster:
    ipam:
      config:
        - subnet: "172.66.0.0/16"